image: dart
script:
  - pub install
  - dartanalyzer web/photobooth.dart
  - pub build

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: googleio-photobooth
    access_key: $AWS_KEY
    secret_key: $AWS_SECRET
    source: build/
    target: photobooth/
